In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
import pickle
import pandas as pd
import numpy as np

In [9]:
## Load the Trained Model,scalar pickle,one hot encoder pickle 

model = tf.keras.models.load_model('model.h5')

## laod the encoder and scaler 
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)  # Load the label encoder for gender from the pickle

with open("label_encoder_gender.pkl", "rb") as file:
    label_encoder_gender = pickle.load(file)  # Load the label encoder for gender from the

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)  # Load the scaler from the pickle file

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [10]:
#Example input data

# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [13]:
# One-hot encode 'Geography'
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Rishabh Pandey\Desktop\ANN Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [14]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [15]:
## Encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [16]:
#Combine one-hot encoded 'Geography' with the rest of the input data
# Combine one-hot encoded Geography with the remaining input data
input_df = pd.concat(
    [input_df.drop(columns=["Geography"]), geo_encoded_df],
    axis=1
)

input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [17]:
## Scaling the input data using the loaded scaler

scaled_input_df = scaler.transform(input_df)
scaled_input_df

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [19]:
## Predict the output using the trained model
prediction=model.predict(scaled_input_df)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

array([[0.0310866]], dtype=float32)

In [20]:
# prediction probability
prediction_prob=prediction[0][0]

In [21]:
prediction_prob

np.float32(0.031086596)

In [22]:
if prediction_prob>0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.