In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
import pickle

In [12]:
data=pd.read_csv('Churn_Modelling.csv')
data.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:
# Data Preprocessing
# Drop unnecessary columns

data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)  # axis=1 means drop columns, axis=0 means drop rows
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
from sklearn.preprocessing import LabelEncoder

## Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [15]:
## Onehote encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()  # drop='first' to avoid dummy variable trap
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [16]:
## Combine one hot encoder columns with original dataset
geo_encoder_df = pd.DataFrame(
    geo_encoder,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography']),
    index=data.index
)

data = pd.concat(
    [data.drop(['Geography'], axis=1), geo_encoder_df],
    axis=1
)

data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [25]:
# split the dataset into features and target variable
X = data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary']

# split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
#scale these features using StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [27]:
#save the encoder and scaler
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)  

with open('scaler.pkl', 'wb') as file:
    pickle.dump(StandardScaler(), file)

## ANN Regression Problem Statement

In [28]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [30]:
#Build the model 
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

# Compile the model
model.compile(optimizer='adam',loss='mean_squared_error', metrics=['mean_absolute_error'])

model.summary()

c:\Users\Rishabh Pandey\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
from tensorflow.keras.callbacks import EarlyStopping
import datetime

# setup TensorBoard callback
log_dir="regression_logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [32]:
# Set up early stopping
early_stopping=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [34]:
# Train the model
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[tensorboard_callback, early_stopping]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13383936000.0000 - mean_absolute_error: 100379.0547 - val_loss: 13008001024.0000 - val_mean_absolute_error: 98523.1719
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13235717120.0000 - mean_absolute_error: 99645.9844 - val_loss: 12710310912.0000 - val_mean_absolute_error: 97018.9844
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12700848128.0000 - mean_absolute_error: 96985.3125 - val_loss: 11932807168.0000 - val_mean_absolute_error: 93087.1250
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11628681216.0000 - mean_absolute_error: 91668.0391 - val_loss: 10618786816.0000 - val_mean_absolute_error: 86461.9141
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10058234880.0000 - mean_absolute_error: 83865.9844 - val_loss: 8907910144.0000 - val_mean_absolute_error: 77864.8281
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8213884928.0000 - mean_absolute_error: 74620.4062 - val_loss: 7088681472.0000 - val_mean_absolute_error: 68826.9219
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6427471360.0000 - mean_absolute_error: 65577.1484 - val_loss: 5510854656.0000 - val_mean_absolute_error: 60960.4570
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5011956224.0000 - mean_absolute_error: 58361.3477 - val_loss: 4409069056.0000 - val_mean_absolute_error: 55289.6094
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4114378752.0000 - mean_absolute_error: 53656.7266 - val_loss: 3812946432.0000 - val_mean_absolute_error: 52238.7109
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3670322432.0000 - mean_absolute_error: 51383.1172 - val_loss: 3569000960.0000 - val_mean_absolute_error: 51058.1055
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3496188416.0000 - mean_absolute_error: 50502.0039 - val_loss: 3487983872.0000 - val_mean_absolute_error: 50677.4570
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3435119360.0000 - mean_absolute_error: 50203.9297 - val_loss: 3459941888.0000 - val_mean_absolute_error: 50555.1914
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3409264384.0000 - mean_absolute_error: 50083.8594 - val_loss: 3445349120.0000 - val_mean_absolute_error: 50486.5664
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3394354944.0000 - mean_absolute_error: 50023.6953 - val_loss: 3433769984.0000 - val_mean_absolute_error: 50432.7266
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3383303936.0000 - mean_absolute_error: 49967.7656 - val_loss: 3423282688.0000 - val_mean_absolute_error: 50383.1445
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3374053888.0000 - mean_absolute_error: 49920.5664 - val_loss: 3414056192.0000 - val_mean_absolute_error: 50342.1953
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3366282240.0000 - mean_absolute_error: 49882.1523 - val_loss: 3405628672.0000 - val_mean_absolute_error: 50303.3633
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3359469568.0000 - mean_absolute_error: 49849.8008 - val_loss: 3398790656.0000 - val_mean_absolute_error: 50269.6719
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3353921280.0000 - mean_absolute_error: 49823.6094 - val_loss: 3393436160.0000 - val_mean_absolute_error: 50252.3164
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3348671744.0000 - mean_absolute_error: 49794.5742 - val_loss: 3388449792.0000 - val_mean_absolute_error: 50229.4102
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3344574208.0000 - mean_absolute_error: 49776.1992 - val_loss: 3384169472.0000 - val_mean_absolute_error: 50214.2188
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3340034304.0000 - mean_absolute_error: 49749.4531 - val_loss: 3380659712.0000 - val_mean_absolute_error: 50205.5000
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3336538880.0000 - mean_absolute_error: 49727.0664 - val_loss: 3378433024.0000 - val_mean_absolute_error: 50202.7461
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3333583872.0000 - mean_absolute_error: 49715.7461 - val_loss: 3373935872.0000 - val_mean_absolute_error: 50183.0312
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3330459648.0000 - mean_absolute_error: 49695.9766 - val_loss: 3371045632.0000 - val_mean_absolute_error: 50168.4219
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3328224512.0000 - mean_absolute_error: 49683.2812 - val_loss: 3368568320.0000 - val_mean_absolute_error: 50158.4688
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3325985024.0000 - mean_absolute_error: 49669.8633 - val_loss: 3366503424.0000 - val_mean_absolute_error: 50152.3828
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3323329536.0000 - mean_absolute_error: 49654.2148 - val_loss: 3364843264.0000 - val_mean_absolute_error: 50146.6406
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3321303296.0000 - mean_absolute_error: 49638.5430 - val_loss: 3364216576.0000 - val_mean_absolute_error: 50149.5586
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3319630336.0000 - mean_absolute_error: 49630.4102 - val_loss: 3361694976.0000 - val_mean_absolute_error: 50133.8008
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3317740800.0000 - mean_absolute_error: 49621.4219 - val_loss: 3360391168.0000 - val_mean_absolute_error: 50128.5078
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3316533504.0000 - mean_absolute_error: 49608.0508 - val_loss: 3359715072.0000 - val_mean_absolute_error: 50128.7734
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3314941184.0000 - mean_absolute_error: 49596.5469 - val_loss: 3358544896.0000 - val_mean_absolute_error: 50124.4492
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3313351936.0000 - mean_absolute_error: 49588.4023 - val_loss: 3357943040.0000 - val_mean_absolute_error: 50125.3477
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3312295424.0000 - mean_absolute_error: 49582.4648 - val_loss: 3357000192.0000 - val_mean_absolute_error: 50120.2891
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3310604800.0000 - mean_absolute_error: 49569.0859 - val_loss: 3357057792.0000 - val_mean_absolute_error: 50125.4219
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3309477888.0000 - mean_absolute_error: 49566.3945 - val_loss: 3355245824.0000 - val_mean_absolute_error: 50111.8359
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3308511488.0000 - mean_absolute_error: 49557.3359 - val_loss: 3356165632.0000 - val_mean_absolute_error: 50121.2969
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3307980288.0000 - mean_absolute_error: 49555.5703 - val_loss: 3355026688.0000 - val_mean_absolute_error: 50115.1250
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3306425856.0000 - mean_absolute_error: 49543.1875 - val_loss: 3354717952.0000 - val_mean_absolute_error: 50113.9570
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3305812224.0000 - mean_absolute_error: 49543.8008 - val_loss: 3354842368.0000 - val_mean_absolute_error: 50117.2617
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3304627200.0000 - mean_absolute_error: 49528.0977 - val_loss: 3354382592.0000 - val_mean_absolute_error: 50119.7891
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3304051712.0000 - mean_absolute_error: 49526.3789 - val_loss: 3354087424.0000 - val_mean_absolute_error: 50122.0547
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3303151104.0000 - mean_absolute_error: 49523.9609 - val_loss: 3353709568.0000 - val_mean_absolute_error: 50117.0469
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3301940736.0000 - mean_absolute_error: 49516.4688 - val_loss: 3352244480.0000 - val_mean_absolute_error: 50106.8984
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3301865216.0000 - mean_absolute_error: 49511.0391 - val_loss: 3352591616.0000 - val_mean_absolute_error: 50113.4141
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3300638976.0000 - mean_absolute_error: 49504.1406 - val_loss: 3355044864.0000 - val_mean_absolute_error: 50132.8164
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3300153344.0000 - mean_absolute_error: 49499.6562 - val_loss: 3355346688.0000 - val_mean_absolute_error: 50136.7695
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3299799296.0000 - mean_absolute_error: 49496.1484 - val_loss: 3354242304.0000 - val_mean_absolute_error: 50127.5859
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3298914304.0000 - mean_absolute_error: 49493.0117 - val_loss: 3354302208.0000 - val_mean_absolute_error: 50127.7109
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3298294528.0000 - mean_absolute_error: 49481.1367 - val_loss: 3352899840.0000 - val_mean_absolute_error: 50119.1758
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3298256896.0000 - mean_absolute_error: 49486.1758 - val_loss: 3352464896.0000 - val_mean_absolute_error: 50113.8125
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3297566208.0000 - mean_absolute_error: 49479.6914 - val_loss: 3353255936.0000 - val_mean_absolute_error: 50119.6016
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3296764416.0000 - mean_absolute_error: 49473.5664 - val_loss: 3353880320.0000 - val_mean_absolute_error: 50129.1797
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3296048896.0000 - mean_absolute_error: 49471.6055 - val_loss: 3353291264.0000 - val_mean_absolute_error: 50126.1523

In [ ]:
%load_ext tensorboard

In [40]:
%tensorboard --logdir regression_logs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [41]:
# Evaluate the model on the test set
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3352244480.0000 - mean_absolute_error: 50106.8984
Test Loss: 3352244480.0, Test MAE: 50106.8984375